# Generated by Django 5.2.7 on 2025-11-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('concluida', models.BooleanField(default=False)),
                ('criada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
